-- ============================================================
-- CGI OS — Compliance, Governance and Integrity. The governance robot's database.
-- Paste this WHOLE file into the Supabase SQL Editor (your own free project)
-- and click Run once. Safe to re-run: it never duplicates or deletes your rows
-- (create-if-not-exists · add-column-if-not-exists · seeds guarded by NOT EXISTS).
--
-- This file is GENERATED by scripts/xlsx_to_sql.py from the demo workbook.
-- Edit supabase/schema.head.sql (the tables) — never this file by hand.
-- ============================================================

-- ------------------------------------------------------------
-- 1) records — the governance register. One row = one thing CGI tracks.
--    category: risk | audit | issue | lesson | cmmi | training | investigation |
--              esg | obligation | gbpms | task
--    classification: internal | restricted (restricted = Investigations; only
--              readable with the second passcode / RESTRICTED_USER_IDS)
-- ------------------------------------------------------------
create table if not exists records (
  id             bigint generated always as identity primary key,
  ref            text,                                   -- register id: ERM-…, IA-…, CO-…, GBPMS-…
  title          text        not null,
  category       text        not null,
  status         text        not null default 'Open',    -- the register's own word (Open, Overdue, In Progress, Closed, Amber …)
  severity       text,                                   -- Critical | High | Medium | Low (drives the autonomy dial)
  owner          text,                                   -- HOD / department accountable
  due_date       date,                                   -- the date that matters for chasing
  value          numeric,                                -- the number that matters (score, days open, completion %)
  classification text        not null default 'internal',
  standard       text,                                   -- ISO 9001 / ISO/IEC 27001 / regulator / GBPMS level
  notes          text,
  meta           jsonb       not null default '{}'::jsonb, -- every original workbook column, verbatim
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
alter table records add column if not exists ref            text;
alter table records add column if not exists severity       text;
alter table records add column if not exists owner          text;
alter table records add column if not exists value          numeric;
alter table records add column if not exists classification text not null default 'internal';
alter table records add column if not exists standard       text;
alter table records add column if not exists updated_at     timestamptz not null default now();
create index if not exists records_category_idx on records (category);
create index if not exists records_ref_idx      on records (ref);

-- ------------------------------------------------------------
-- 2) agent_actions — the proposals/approvals table. THE HITL HEART.
--    A robot's wish is written here ONCE, a human (or the autopilot dial) decides,
--    then it's claimed + executed exactly once. Never fold this into records.
-- ------------------------------------------------------------
create table if not exists agent_actions (
  id                bigint generated always as identity primary key,
  agent_key         text        not null,
  idempotency_key   text        not null unique,      -- dedupe: one wish per event
  payload           jsonb       not null,             -- written once, immutable
  status            text        not null default 'proposed',
                    -- proposed | approved | rejected | expired | executing | executed | failed
  proposed_at       timestamptz not null default now(),
  expires_at        timestamptz not null default (now() + interval '24 hours'),
  decided_at        timestamptz,
  executed_at       timestamptz,
  approver_chat_id  bigint,                            -- null = decided by the robot (autopilot)
  result            jsonb,
  error             text,
  notify_chat_id    bigint,                            -- captured from sendWithButtons()...
  notify_message_id bigint                             -- ...so the in-app approve path can strip the buttons
);
alter table agent_actions add column if not exists notify_chat_id    bigint;
alter table agent_actions add column if not exists notify_message_id bigint;
alter table agent_actions add column if not exists result            jsonb;
alter table agent_actions add column if not exists error             text;

-- ------------------------------------------------------------
-- 3) agent_runs — one row per agent invocation. Feeds the Activity view.
-- ------------------------------------------------------------
create table if not exists agent_runs (
  id          bigint generated always as identity primary key,
  agent_key   text        not null,
  started_at  timestamptz not null default now(),
  finished_at timestamptz,
  outcome     text,                                    -- ok | escalated | failed | noop ...
  detail      jsonb       not null default '{}'::jsonb
);

-- ------------------------------------------------------------
-- 4) bot_memory — the bot's short-term memory + per-chat daily counters.
-- ------------------------------------------------------------
create table if not exists bot_memory (
  chat_id     bigint      primary key,
  turns       jsonb       not null default '[]'::jsonb,
  counters    jsonb       not null default '{}'::jsonb,
  updated_at  timestamptz not null default now()
);
alter table bot_memory add column if not exists counters jsonb not null default '{}'::jsonb;

-- ------------------------------------------------------------
-- 5) tg_updates — Telegram delivery dedupe (Telegram RETRIES un-acked webhooks).
-- ------------------------------------------------------------
create table if not exists tg_updates (
  update_id   bigint      primary key,
  received_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 6) watch_log — what the Regulatory Watch searched and found, run by run, so a
--    proposal can always be traced back to the search that produced it.
-- ------------------------------------------------------------
create table if not exists watch_log (
  id          bigint generated always as identity primary key,
  ran_at      timestamptz not null default now(),
  source      text        not null,                    -- gmail | web
  query       text,
  findings    jsonb       not null default '[]'::jsonb,
  proposed    int         not null default 0
);

-- ------------------------------------------------------------
-- Security: server-side only. The Next.js server uses the SERVICE_ROLE key,
-- which bypasses RLS. Enabling RLS with NO policies means anon/public gets
-- nothing — exactly what we want. Never expose these rows via a public route.
-- ------------------------------------------------------------
alter table records       enable row level security;
alter table agent_actions enable row level security;
alter table agent_runs    enable row level security;
alter table bot_memory    enable row level security;
alter table tg_updates    enable row level security;
alter table watch_log     enable row level security;
